[rule]
description = """
This rule detects three PTRACE_POKETEXT/PTRACE_POKEDATA requests from one process against distinct addresses in another
process within one second. Rapid writes to multiple target addresses through ptrace can indicate shellcode being copied
into a target process and may occur during process injection.
"""
id = "051e67fd-62f5-4b25-bcb5-06351114c9a9"
license = "Elastic License v2"
name = "Multiple Distinct Ptrace POKETEXT/POKEDATA Writes"
os_list = ["linux"]
reference = [
    "https://man7.org/linux/man-pages/man2/ptrace.2.html",
    "https://www.akamai.com/blog/security-research/the-definitive-guide-to-linux-process-injection",
]
version = "1.0.4"

query = '''
sequence by process.entity_id, process.Ext.ptrace.child_pid with maxspan=1s
  [process where event.type == "start" and event.action == "ptrace" and process.Ext.ptrace.request in (4, 5) and
   process.Ext.ptrace.addr >= 4096 and process.executable != null and
   not (
     process.executable like (
       "/opt/dynatrace/oneagent/agent/lib64/oneagenthelper", "/usr/libexec/platform-python*",
       "/usr/imperva/ragent/bin/InjectionManager", "/usr/bin/reptyr"
     ) or
     process.parent.executable like "/var/lib/oracle-cloud-agent/plugins/oci-osmh/osmh-agent/*/osmh"
   )
  ] as event0
  [process where event.type == "start" and event.action == "ptrace" and process.Ext.ptrace.request in (4, 5) and
   (process.Ext.ptrace.addr - event0.process.Ext.ptrace.addr) in (4, 8)] as event1
  [process where event.type == "start" and event.action == "ptrace" and process.Ext.ptrace.request in (4, 5) and
   (process.Ext.ptrace.addr - event1.process.Ext.ptrace.addr) in (4, 8)]
'''

min_endpoint_version = "9.1.4"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 1

[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 2

[[actions]]
action = "kill_process"
field = "process.parent.entity_id"
state = 0

[[actions]]
action = "kill_process"
field = "process.parent.entity_id"
state = 1

[[actions]]
action = "kill_process"
field = "process.parent.entity_id"
state = 2

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"
[[threat.technique.subtechnique]]
id = "T1055.008"
name = "Ptrace System Calls"
reference = "https://attack.mitre.org/techniques/T1055/008/"



[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "9.1.4"
